version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev.yml
    container_name: social-analytics-challenge
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: social-analytics-challenge-db
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  redis-data:
